"""Minimal romance-light + mystery-lite concepts for P2 golden/corpus."""

ROMANCE_GATE_CONCEPT = {
    "concept_status": "ready",
    "schema_version": "1.0",
    "target_language": "en",
    "title": "Romance Gate",
    "pen_name": "P2 Fixture",
    "chapter_count": 3,
    "logline": "Two keepers renegotiate a locked gate without inventing crimes.",
    "author_directive": (
        "Follow the locked chapter map. No invented names. No medical claims. "
        + ("x" * 120)
    ),
    "surface_plot": "Lina and Cole reopen a sealed garden gate under watch.",
    "true_plot": "The gate was never broken; the lock log was delayed on purpose.",
    "intentional_early_reveal": False,
    "pov": {
        "character": "Lina Reed",
        "mode": "third_limited",
        "tense": "past",
        "single_pov": True,
    },
    "characters": [
        {"name": "Lina Reed", "role": "protagonist"},
        {"name": "Cole Hart", "role": "love_interest"},
    ],
    "chapter_map": {
        "1": {
            "title": "The Latch",
            "day_or_time_anchor": "Evening one",
            "pov_knows_at_start": ["The garden gate is sealed."],
            "may_observe": ["Cole arrives with the spare key card."],
            "must_happen": ["Lina Reed inventories the latch without forcing it."],
            "must_not": ["Invent unsupported medical diagnosis."],
            "must_not_happen": ["Invent unsupported medical diagnosis."],
            "reveal_ids_opened": [],
            "clue_ids_planted": [],
            "clue_ids_paid_off": [],
            "prop_actions": [],
            "relationship_turn": "Caution softens into shared duty.",
            "primary_turn": "The latch is logged, not broken.",
            "spice_level": 0,
        },
        "2": {
            "title": "Shared Watch",
            "day_or_time_anchor": "Morning two",
            "pov_knows_at_start": ["The latch log is incomplete."],
            "may_observe": ["Cole Hart waits without touching the gate."],
            "must_happen": ["Lina Reed and Cole Hart compare key-card times."],
            "must_not": ["They leave the garden."],
            "must_not_happen": ["They leave the garden."],
            "reveal_ids_opened": ["RG1"],
            "clue_ids_planted": [],
            "clue_ids_paid_off": [],
            "prop_actions": [],
            "relationship_turn": "Trust is provisional and earned.",
            "primary_turn": "The delayed log becomes visible.",
            "spice_level": 0,
        },
        "3": {
            "title": "Open Air",
            "day_or_time_anchor": "Dusk three",
            "pov_knows_at_start": ["The delay was deliberate."],
            "may_observe": ["The gate opens on schedule."],
            "must_happen": ["Lina Reed records the on-time open with Cole Hart present."],
            "must_not": ["They invent a third keeper."],
            "must_not_happen": ["They invent a third keeper."],
            "reveal_ids_opened": [],
            "clue_ids_planted": [],
            "clue_ids_paid_off": [],
            "prop_actions": [],
            "relationship_turn": "Duty becomes chosen closeness.",
            "primary_turn": "The garden opens without a crime story.",
            "spice_level": 1,
        },
    },
    "required_reveal_schedule": [
        {
            "id": "RG1",
            "fact": "The lock log was delayed on purpose by the prior keeper.",
            "reader_reveal_chapter": 2,
            "pov_knows_chapter": 2,
            "reveal_type": "observation",
            "prerequisite_reveals": [],
            "required_clues": [],
            "must_remain_hidden_before": 1,
            "allowed_foreshadowing_before": "incomplete log mention",
        }
    ],
    "ending_book1": "The garden opens on the recorded schedule.",
    "hook_book2": "A second delayed log appears elsewhere.",
    "must_include": ["Evidence remains observable."],
    "must_avoid": ["Unsupported diagnosis.", "Invented proper nouns."],
    "notes": "Zero-Trust Romance lite fixture for P2 golden.",
    "romance_doctrine": {
        "rules": ["Competence over confession", "Zero-Trust Romance"],
        "forbidden_framings": ["Rescue fantasy"],
    },
}


MYSTERY_LITE_CONCEPT = {
    "concept_status": "ready",
    "schema_version": "1.0",
    "target_language": "en",
    "title": "Mystery Lite Gate",
    "pen_name": "P2 Fixture",
    "chapter_count": 4,
    "logline": "A clerk tracks a delayed evidence stamp without inventing forensics.",
    "author_directive": (
        "Follow the locked chapter map. No invented names. No medical claims. "
        + ("y" * 120)
    ),
    "surface_plot": "Nora follows a delayed stamp trail across four nights.",
    "true_plot": "The stamp delay hid a swapped envelope already logged.",
    "intentional_early_reveal": False,
    "pov": {
        "character": "Nora Quill",
        "mode": "third_limited",
        "tense": "past",
        "single_pov": True,
    },
    "characters": [
        {"name": "Nora Quill", "role": "protagonist"},
        {"name": "Evan Pike", "role": "antagonist"},
    ],
    "chapter_map": {
        "1": {
            "title": "Stamp Desk",
            "day_or_time_anchor": "Night one",
            "pov_knows_at_start": ["The stamp log is late."],
            "may_observe": ["Evan Pike avoids the desk lamp."],
            "must_happen": ["Nora Quill copies the late stamp row."],
            "must_not": ["Invent unsupported medical diagnosis."],
            "must_not_happen": ["Invent unsupported medical diagnosis."],
            "reveal_ids_opened": [],
            "clue_ids_planted": ["CL1"],
            "clue_ids_paid_off": [],
            "prop_actions": [],
            "relationship_turn": "Suspicion stays professional.",
            "primary_turn": "The late row is recorded.",
            "spice_level": 0,
        },
        "2": {
            "title": "Envelope Gap",
            "day_or_time_anchor": "Night two",
            "pov_knows_at_start": ["The late stamp row exists."],
            "may_observe": ["The envelope weight does not match the log."],
            "must_happen": ["Nora Quill weighs the envelope against the log."],
            "must_not": ["Invent unsupported medical diagnosis."],
            "must_not_happen": ["Invent unsupported medical diagnosis."],
            "reveal_ids_opened": ["ML1"],
            "clue_ids_planted": [],
            "clue_ids_paid_off": ["CL1"],
            "prop_actions": [],
            "relationship_turn": "Evan Pike presses for a quiet close.",
            "primary_turn": "Weight mismatch is visible to Nora.",
            "spice_level": 0,
        },
        "3": {
            "title": "Quiet Close",
            "day_or_time_anchor": "Night three",
            "pov_knows_at_start": ["The envelope weight is wrong."],
            "may_observe": ["Evan Pike offers a corrected stamp."],
            "must_happen": ["Nora Quill refuses the corrected stamp."],
            "must_not": ["Invent unsupported medical diagnosis."],
            "must_not_happen": ["Invent unsupported medical diagnosis."],
            "reveal_ids_opened": [],
            "clue_ids_planted": [],
            "clue_ids_paid_off": [],
            "prop_actions": [],
            "relationship_turn": "Pressure replaces courtesy.",
            "primary_turn": "Correction is refused.",
            "spice_level": 0,
        },
        "4": {
            "title": "Logged Swap",
            "day_or_time_anchor": "Night four",
            "pov_knows_at_start": ["The correction was a cover."],
            "may_observe": ["The swapped envelope id is in the prior log."],
            "must_happen": ["Nora Quill matches the swapped envelope to the prior log."],
            "must_not": ["Invent unsupported medical diagnosis."],
            "must_not_happen": ["Invent unsupported medical diagnosis."],
            "reveal_ids_opened": ["ML2"],
            "clue_ids_planted": [],
            "clue_ids_paid_off": [],
            "prop_actions": [],
            "relationship_turn": "The desk closes without partnership fantasy.",
            "primary_turn": "The swap is proven from the log.",
            "spice_level": 0,
        },
    },
    "required_reveal_schedule": [
        {
            "id": "ML1",
            "fact": "The envelope weight does not match the logged contents.",
            "reader_reveal_chapter": 2,
            "pov_knows_chapter": 2,
            "reveal_type": "observation",
            "prerequisite_reveals": [],
            "required_clues": ["CL1"],
            "must_remain_hidden_before": 1,
            "allowed_foreshadowing_before": "late stamp mention",
        },
        {
            "id": "ML2",
            "fact": "The stamp delay hid a swapped envelope already logged.",
            "reader_reveal_chapter": 3,
            "pov_knows_chapter": 4,
            "reveal_type": "inference",
            "prerequisite_reveals": ["ML1"],
            "required_clues": [],
            "must_remain_hidden_before": 3,
            "allowed_foreshadowing_before": "refuse corrected stamp",
        },
    ],
    "clues": [
        {
            "id": "CL1",
            "description": "Late stamp row with mismatched envelope weight later.",
            "plant_chapter": 1,
            "payoff_chapter": 2,
        }
    ],
    "ending_book1": "Nora Quill proves the swap from the prior log.",
    "hook_book2": "A second stamp desk shows the same delay pattern.",
    "must_include": ["Evidence remains observable."],
    "must_avoid": ["Unsupported diagnosis.", "Invented proper nouns."],
    "notes": "Mystery-lite fixture for P2 Memory/Strategy corpus.",
}
